/*
SQLyog Community v13.2.1 (64 bit)
MySQL - 8.0.13 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `recipe_process` (
	`id` int (11),
	`preparation_time` varchar (30),
	`cooking_time` varchar (30),
	`ingredients` text ,
	`recipe_procedure` text ,
	`serve` varchar (765)
); 
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`) values('1','10 mins','20 mins','4 medium ripe tomatoes,  \r\n1 small onion, finely chopped  \r\n2 garlic cloves, crushed  \r\n1-inch piece of ginger, grated  \r\n1 tsp butter or ghee,\r\n1/4 tsp black pepper powder,  \r\nSalt to taste,\r\n2 cups water ,\r\nFresh coriander leaves for garnish','1. Wash and roughly chop the tomatoes.  \r\n2. In a pan, heat the butter or ghee over medium heat. Add the chopped onion, garlic, and ginger, and sauté until the onion becomes translucent.  \r\n3. Add the chopped tomatoes and cook for 5 to 7 minutes, or until they soften.  \r\n4. Pour in 2 cups of water. Add salt and black pepper, then let the mixture simmer for about 10 minutes.  \r\n5. Allow it to cool slightly, then blend into a smooth puree using a mixer or hand blender.  \r\n6. Strain the puree to remove seeds and skin for a smoother texture.  \r\n7. Reheat the strained soup over low heat. Taste and adjust the seasoning if needed. Stir in the cream if using.  \r\n8. Serve hot, garnished with fresh coriander leaves.','2–3 servings');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`) values('2','30 mins','20 mins',' For the Dosa batter:\r\n    1 cup rice\r\n    1/3 cup split urad dal (black gram)\r\n    1/2 tsp fenugreek seeds (optional)\r\n    Water (for soaking and grinding)\r\n    Salt to taste\r\n    \r\n    For the Potato filling:\r\n    3 large potatoes, boiled and mashed\r\n    1 onion, finely chopped\r\n    1 green chili, chopped (optional)\r\n    1 tsp mustard seeds\r\n    1 tsp turmeric powder\r\n    1 tsp cumin seeds\r\n    1/2 tsp hing (asafoetida)\r\n    1 tbsp oil\r\n    Salt to taste\r\n    Fresh coriander leaves, chopped (optional)','1. Rinse the rice, urad dal, and fenugreek seeds. Soak them separately for at least 4-6 hours or overnight.  \r\n    2. Drain the soaked ingredients and grind them together in a blender or wet grinder, adding enough water to form a smooth batter. The consistency should be like pancake batter.  \r\n    3. Ferment the batter for 8-12 hours or overnight in a warm place.  \r\n    4. For the potato filling: In a pan, heat oil and add mustard seeds. Once they crackle, add cumin seeds, hing, and turmeric powder.  \r\n    5. Add chopped onions and green chilies, sautéing until the onions become soft.  \r\n    6. Add the boiled and mashed potatoes, mix well, and cook for 2-3 minutes. Season with salt and stir in chopped coriander leaves. Set aside.  \r\n    7. Heat a non-stick griddle or dosa pan. Pour a ladleful of dosa batter onto the pan and spread it into a thin circle. Drizzle some oil around the edges.  \r\n    8. Cook the dosa until the bottom is golden brown and crispy.  \r\n    9. Place a portion of the potato filling in the center of the dosa, fold it in half, and serve hot.  \r\n    10. Repeat for the remaining dosas. Serve with chutney and sambar.','4-5 servings');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`) values('3','30 mins','45 mins','For Idli batter:\r\n    2 cups rice\r\n    1 cup split urad dal (black gram)\r\n    1/2 tsp fenugreek seeds (optional)\r\n    Water (for soaking and grinding)\r\n    Salt to taste\r\n    \r\n    For Sambar:\r\n    1 cup toor dal (yellow pigeon peas)\r\n    1 onion, finely chopped\r\n    1 tomato, chopped\r\n    1 carrot, diced\r\n    1 potato, diced\r\n    1/2 cup tamarind pulp\r\n    1 tbsp sambar powder\r\n    1 tsp mustard seeds\r\n    1 tsp cumin seeds\r\n    1/4 tsp turmeric powder\r\n    2-3 dried red chilies\r\n    1-2 tbsp oil\r\n    Salt to taste\r\n    Fresh coriander leaves, chopped (for garnish)','1. Rinse the rice, urad dal, and fenugreek seeds. Soak them separately for 4-6 hours or overnight.  \r\n    2. Drain and grind the soaked ingredients into a smooth batter with water, resembling pancake batter consistency.  \r\n    3. Allow the batter to ferment for 8-12 hours or overnight.  \r\n    4. To make the sambar, cook the toor dal in a pressure cooker with 2 cups of water for 3-4 whistles.  \r\n    5. In a pan, heat oil and add mustard seeds, cumin seeds, dried red chilies, and turmeric. Once the mustard seeds pop, add onions, tomatoes, and cook until soft.  \r\n    6. Add diced carrots, potatoes, and tamarind pulp. Cook for 10 minutes.  \r\n    7. Add the cooked toor dal, sambar powder, salt, and 1-2 cups of water. Bring to a boil and simmer for 15 minutes.  \r\n    8. Garnish with fresh coriander leaves.  \r\n    9. Pour the fermented idli batter into idli molds and steam for 10-15 minutes.  \r\n    10. Serve hot idlis with sambar and coconut chutney.','4-5 servings');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`) values('4','15 mins','0 mins','1 cucumber, finely chopped\r\n    1 tomato, chopped\r\n    1 carrot, julienned\r\n    1/2 red onion, thinly sliced\r\n    1/4 cup corn kernels\r\n    1/4 cup bell pepper, chopped\r\n    1 tbsp olive oil\r\n    1 tbsp lemon juice\r\n    Salt and pepper to taste\r\n    Fresh coriander or parsley for garnish','1. Wash and prepare all the vegetables.  \r\n    2. In a large mixing bowl, combine cucumber, tomato, carrot, onion, corn, and bell pepper.  \r\n    3. Drizzle olive oil and lemon juice over the salad.  \r\n    4. Season with salt and pepper.  \r\n    5. Toss the ingredients together until well combined.  \r\n    6. Garnish with fresh coriander or parsley.  \r\n    7. Serve immediately or chill for a few minutes before serving.','2-3 servings');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`) values('5','20 mins','30 mins','1 1/2 cups all-purpose flour\r\n    1 cup sugar\r\n    1/2 cup cocoa powder\r\n    1 1/2 tsp baking powder\r\n    1/2 tsp baking soda\r\n    1/4 tsp salt\r\n    1/2 cup milk\r\n    1/2 cup vegetable oil\r\n    2 large eggs\r\n    1 tsp vanilla extract\r\n    1/2 cup boiling water\r\n    For Frosting:\r\n    1/2 cup butter, softened\r\n    1/4 cup cocoa powder\r\n    2 cups powdered sugar\r\n    1/4 cup milk\r\n    1 tsp vanilla extract','1. Preheat your oven to 350°F (175°C) and grease two 9-inch round cake pans.  \r\n    2. In a large bowl, mix together the flour, sugar, cocoa powder, baking powder, baking soda, and salt.  \r\n    3. Add milk, vegetable oil, eggs, and vanilla extract to the dry ingredients and beat well until smooth.  \r\n    4. Gradually add boiling water, mixing until the batter is smooth and thin.  \r\n    5. Pour the batter evenly into the prepared cake pans and bake for 30 minutes or until a toothpick inserted comes out clean.  \r\n    6. Let the cakes cool in the pans for 10 minutes before transferring them to a wire rack to cool completely.  \r\n    7. For the frosting, beat together the softened butter, cocoa powder, powdered sugar, milk, and vanilla until smooth and creamy.  \r\n    8. Frost the cooled cakes with the chocolate frosting.  \r\n    9. Serve and enjoy!','8-10 servings');
