/*
SQLyog Community v13.2.1 (64 bit)
MySQL - 8.0.13 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `recipe_process` (
	`id` int (11),
	`preparation_time` varchar (30),
	`cooking_time` varchar (30),
	`ingredients` text ,
	`recipe_procedure` text ,
	`serve` varchar (765),
	`recipe_id` int (11)
); 
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('1','10 mins','20 mins','4 medium ripe tomatoes,  \r\n1 small onion, finely chopped  \r\n2 garlic cloves, crushed  \r\n1-inch piece of ginger, grated  \r\n1 tsp butter or ghee,\r\n1/4 tsp black pepper powder,  \r\nSalt to taste,\r\n2 cups water ,\r\nFresh coriander leaves for garnish','1. Wash and roughly chop the tomatoes.  \r\n2. In a pan, heat the butter or ghee over medium heat. Add the chopped onion, garlic, and ginger, and sauté until the onion becomes translucent.  \r\n3. Add the chopped tomatoes and cook for 5 to 7 minutes, or until they soften.  \r\n4. Pour in 2 cups of water. Add salt and black pepper, then let the mixture simmer for about 10 minutes.  \r\n5. Allow it to cool slightly, then blend into a smooth puree using a mixer or hand blender.  \r\n6. Strain the puree to remove seeds and skin for a smoother texture.  \r\n7. Reheat the strained soup over low heat. Taste and adjust the seasoning if needed. Stir in the cream if using.  \r\n8. Serve hot, garnished with fresh coriander leaves.','2–3 servings','1');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('2','30 mins','20 mins',' For the Dosa batter:\r\n    1 cup rice\r\n    1/3 cup split urad dal (black gram)\r\n    1/2 tsp fenugreek seeds (optional)\r\n    Water (for soaking and grinding)\r\n    Salt to taste\r\n    \r\n    For the Potato filling:\r\n    3 large potatoes, boiled and mashed\r\n    1 onion, finely chopped\r\n    1 green chili, chopped (optional)\r\n    1 tsp mustard seeds\r\n    1 tsp turmeric powder\r\n    1 tsp cumin seeds\r\n    1/2 tsp hing (asafoetida)\r\n    1 tbsp oil\r\n    Salt to taste\r\n    Fresh coriander leaves, chopped (optional)','1. Rinse the rice, urad dal, and fenugreek seeds. Soak them separately for at least 4-6 hours or overnight.  \r\n    2. Drain the soaked ingredients and grind them together in a blender or wet grinder, adding enough water to form a smooth batter. The consistency should be like pancake batter.  \r\n    3. Ferment the batter for 8-12 hours or overnight in a warm place.  \r\n    4. For the potato filling: In a pan, heat oil and add mustard seeds. Once they crackle, add cumin seeds, hing, and turmeric powder.  \r\n    5. Add chopped onions and green chilies, sautéing until the onions become soft.  \r\n    6. Add the boiled and mashed potatoes, mix well, and cook for 2-3 minutes. Season with salt and stir in chopped coriander leaves. Set aside.  \r\n    7. Heat a non-stick griddle or dosa pan. Pour a ladleful of dosa batter onto the pan and spread it into a thin circle. Drizzle some oil around the edges.  \r\n    8. Cook the dosa until the bottom is golden brown and crispy.  \r\n    9. Place a portion of the potato filling in the center of the dosa, fold it in half, and serve hot.  \r\n    10. Repeat for the remaining dosas. Serve with chutney and sambar.','4-5 servings','2');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('3','30 mins','45 mins','For Idli batter:\r\n    2 cups rice\r\n    1 cup split urad dal (black gram)\r\n    1/2 tsp fenugreek seeds (optional)\r\n    Water (for soaking and grinding)\r\n    Salt to taste\r\n    \r\n    For Sambar:\r\n    1 cup toor dal (yellow pigeon peas)\r\n    1 onion, finely chopped\r\n    1 tomato, chopped\r\n    1 carrot, diced\r\n    1 potato, diced\r\n    1/2 cup tamarind pulp\r\n    1 tbsp sambar powder\r\n    1 tsp mustard seeds\r\n    1 tsp cumin seeds\r\n    1/4 tsp turmeric powder\r\n    2-3 dried red chilies\r\n    1-2 tbsp oil\r\n    Salt to taste\r\n    Fresh coriander leaves, chopped (for garnish)','1. Rinse the rice, urad dal, and fenugreek seeds. Soak them separately for 4-6 hours or overnight.  \r\n    2. Drain and grind the soaked ingredients into a smooth batter with water, resembling pancake batter consistency.  \r\n    3. Allow the batter to ferment for 8-12 hours or overnight.  \r\n    4. To make the sambar, cook the toor dal in a pressure cooker with 2 cups of water for 3-4 whistles.  \r\n    5. In a pan, heat oil and add mustard seeds, cumin seeds, dried red chilies, and turmeric. Once the mustard seeds pop, add onions, tomatoes, and cook until soft.  \r\n    6. Add diced carrots, potatoes, and tamarind pulp. Cook for 10 minutes.  \r\n    7. Add the cooked toor dal, sambar powder, salt, and 1-2 cups of water. Bring to a boil and simmer for 15 minutes.  \r\n    8. Garnish with fresh coriander leaves.  \r\n    9. Pour the fermented idli batter into idli molds and steam for 10-15 minutes.  \r\n    10. Serve hot idlis with sambar and coconut chutney.','4-5 servings','3');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('4','15 mins','0 mins','1 cucumber, finely chopped\r\n    1 tomato, chopped\r\n    1 carrot, julienned\r\n    1/2 red onion, thinly sliced\r\n    1/4 cup corn kernels\r\n    1/4 cup bell pepper, chopped\r\n    1 tbsp olive oil\r\n    1 tbsp lemon juice\r\n    Salt and pepper to taste\r\n    Fresh coriander or parsley for garnish','1. Wash and prepare all the vegetables.  \r\n    2. In a large mixing bowl, combine cucumber, tomato, carrot, onion, corn, and bell pepper.  \r\n    3. Drizzle olive oil and lemon juice over the salad.  \r\n    4. Season with salt and pepper.  \r\n    5. Toss the ingredients together until well combined.  \r\n    6. Garnish with fresh coriander or parsley.  \r\n    7. Serve immediately or chill for a few minutes before serving.','2-3 servings','4');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('5','20 mins','30 mins','1 1/2 cups all-purpose flour\r\n    1 cup sugar\r\n    1/2 cup cocoa powder\r\n    1 1/2 tsp baking powder\r\n    1/2 tsp baking soda\r\n    1/4 tsp salt\r\n    1/2 cup milk\r\n    1/2 cup vegetable oil\r\n    2 large eggs\r\n    1 tsp vanilla extract\r\n    1/2 cup boiling water\r\n    For Frosting:\r\n    1/2 cup butter, softened\r\n    1/4 cup cocoa powder\r\n    2 cups powdered sugar\r\n    1/4 cup milk\r\n    1 tsp vanilla extract','1. Preheat your oven to 350°F (175°C) and grease two 9-inch round cake pans.  \r\n    2. In a large bowl, mix together the flour, sugar, cocoa powder, baking powder, baking soda, and salt.  \r\n    3. Add milk, vegetable oil, eggs, and vanilla extract to the dry ingredients and beat well until smooth.  \r\n    4. Gradually add boiling water, mixing until the batter is smooth and thin.  \r\n    5. Pour the batter evenly into the prepared cake pans and bake for 30 minutes or until a toothpick inserted comes out clean.  \r\n    6. Let the cakes cool in the pans for 10 minutes before transferring them to a wire rack to cool completely.  \r\n    7. For the frosting, beat together the softened butter, cocoa powder, powdered sugar, milk, and vanilla until smooth and creamy.  \r\n    8. Frost the cooled cakes with the chocolate frosting.  \r\n    9. Serve and enjoy!','8-10 servings','5');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('27','2 mins','5 mins','1 cup water\r\n1 tbsp instant coffee\r\n2 tsp sugar (adjust to taste)\r\n1/4 cup milk (optional)','1. Boil 1 cup of water in a saucepan.  \r\n2. Add instant coffee and sugar to the boiling water.  \r\n3. Stir well until dissolved.  \r\n4. If desired, add milk and bring to a gentle boil.  \r\n5. Pour into a cup and serve hot.','1 serving','6');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('28','10 mins','0 mins','4 fresh oranges\r\nIce cubes (optional)\r\nMint leaves for garnish (optional)','1. Wash and peel the oranges if needed.  \r\n2. Cut the oranges in half and extract juice using a manual or electric juicer.  \r\n3. Strain the juice to remove pulp and seeds, if desired.  \r\n4. Pour the juice into glasses with ice cubes.  \r\n5. Garnish with mint leaves and serve chilled.','2 servings','7');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('29','15 mins','25 mins','200g paneer, cubed\r\n2 tbsp butter\r\n1 onion, chopped\r\n2 tomatoes, pureed\r\n1 tsp ginger-garlic paste\r\n1/4 cup cream\r\n1/2 tsp turmeric\r\n1 tsp red chili powder\r\n1 tsp garam masala\r\n1/2 tsp cumin seeds\r\nSalt to taste\r\nFresh coriander for garnish','1. Heat butter in a pan and add cumin seeds.  \r\n2. Add chopped onions and sauté until golden brown.  \r\n3. Add ginger-garlic paste and cook for a minute.  \r\n4. Pour in the tomato puree and cook until oil separates.  \r\n5. Add turmeric, red chili powder, and salt. Mix well.  \r\n6. Add paneer cubes and cook for 5–7 minutes.  \r\n7. Stir in cream and garam masala. Simmer for 2–3 minutes.  \r\n8. Garnish with coriander and serve hot with naan or rice.','2-3 servings','8');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('30','5 mins','10 mins','2 cups water\r\n1 cup milk\r\n2 tsp black tea leaves\r\n1 inch ginger (crushed)\r\n2 cardamom pods (crushed)\r\n2 tsp sugar (adjust to taste)','1. Boil water with crushed ginger and cardamom.  \r\n2. Add tea leaves and boil for 2 minutes.  \r\n3. Pour in milk and bring to a boil.  \r\n4. Add sugar and simmer for a minute.  \r\n5. Strain and serve hot.','2 servings','9');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('31','15 mins','15 mins','1 cup dosa batter\r\n1/4 cup chopped onions\r\n1/4 cup chopped tomatoes\r\n2 tbsp chopped coriander\r\n1 green chili, finely chopped\r\nSalt to taste\r\nOil for cooking','1. Heat a non-stick pan and lightly grease it.  \r\n2. Pour a ladle of dosa batter and spread slightly thick.  \r\n3. Sprinkle onions, tomatoes, coriander, and green chili.  \r\n4. Drizzle a little oil around the edges.  \r\n5. Cook on medium heat until bottom is golden.  \r\n6. Flip and cook the other side lightly.  \r\n7. Serve hot with chutney or sambar.','2 uttapams','10');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('32','5 mins','0 mins','2 ripe bananas\r\n1 cup milk (or almond milk)\r\n1 tbsp honey\r\n1/4 tsp cinnamon (optional)\r\nIce cubes','1. Peel and slice the bananas.  \r\n2. Add all ingredients to a blender.  \r\n3. Blend until smooth and creamy.  \r\n4. Pour into glasses and serve chilled.','2 servings','11');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('33','10 mins','0 mins','1 medium beetroot, peeled and chopped\r\n1 apple (optional)\r\n1/2 inch ginger\r\n1/2 lemon\r\nWater as needed','1. Add beetroot, apple, and ginger to a blender.  \r\n2. Blend with a little water until smooth.  \r\n3. Strain through a fine sieve.  \r\n4. Add lemon juice and mix well.  \r\n5. Serve immediately.','1-2 servings','12');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('34','5 mins','0 mins','1 lemon\r\n10 mint leaves\r\n1 tbsp sugar\r\n1/4 tsp salt\r\n1.5 cups chilled water\r\nIce cubes','1. Squeeze lemon juice into a blender.  \r\n2. Add mint leaves, sugar, salt, and a little water.  \r\n3. Blend until mint is crushed.  \r\n4. Add remaining water and mix well.  \r\n5. Serve over ice cubes.','2 servings','13');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('35','1 hr','20 mins','1.5 cups whole wheat flour\r\n1 tsp dry yeast\r\n1/2 tsp sugar\r\n3/4 cup warm water\r\n1 tbsp olive oil\r\nSalt to taste\r\nPizza sauce\r\n1/2 cup chopped vegetables (bell peppers, onion, etc.)\r\n1/2 cup grated mozzarella cheese','1. Activate yeast with warm water and sugar.  \r\n2. Mix with flour, salt, and olive oil to form dough.  \r\n3. Let dough rise for 1 hour.  \r\n4. Preheat oven to 220°C (428°F).  \r\n5. Roll out dough and place on a baking tray.  \r\n6. Spread pizza sauce, add veggies and cheese.  \r\n7. Bake for 15–20 minutes until crust is golden and cheese melts.','2-3 servings','14');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('36','5 mins','0 mins','1 cup mixed berries (strawberries, blueberries, raspberries)\r\n1 cup yogurt or milk\r\n1 tbsp honey or sugar\r\nIce cubes','1. Wash and prepare the berries.  \r\n2. Add berries, yogurt/milk, honey, and ice cubes to blender.  \r\n3. Blend until smooth and creamy.  \r\n4. Pour into glasses and serve chilled.','2 servings','15');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('37','20 mins','15 mins','1 cup whole wheat flour\r\n1/2 tsp yeast\r\n1/2 tsp sugar\r\n1/2 cup warm water\r\nSalt to taste\r\n1 burger patty (vegetable or meat)\r\nLettuce, tomato, onion slices\r\nSauce of choice','1. Prepare dough by mixing flour, yeast, sugar, salt, and warm water.  \r\n2. Let dough rise for 15 minutes.  \r\n3. Shape dough into burger buns and bake or cook on skillet until golden.  \r\n4. Cook burger patty separately.  \r\n5. Assemble burger with bun, patty, vegetables, and sauce.','2 servings','16');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('38','10 mins','0 mins','2 ripe mangoes\r\n1 cup water or milk\r\nSugar or honey to taste\r\nIce cubes','1. Peel and chop mangoes.  \r\n2. Blend mango pieces with water/milk and sweetener until smooth.  \r\n3. Add ice cubes and blend briefly.  \r\n4. Serve chilled.','2 servings','17');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('39','15 mins','25 mins','1/2 cup butter\r\n1 cup sugar\r\n2 eggs\r\n1/3 cup cocoa powder\r\n1/2 cup flour\r\n1/4 tsp salt\r\n1/4 tsp baking powder','1. Preheat oven to 175°C (350°F).  \r\n2. Melt butter and mix with sugar.  \r\n3. Add eggs one at a time and stir well.  \r\n4. Sift cocoa powder, flour, salt, and baking powder and fold into mixture.  \r\n5. Pour batter into greased pan.  \r\n6. Bake for 20-25 minutes.  \r\n7. Cool before cutting into squares.','8 servings','18');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('40','10 mins','15 mins','200g noodles\r\n1 cup mixed vegetables (carrots, capsicum, beans)\r\n2 tbsp soy sauce\r\n1 tbsp oil\r\n2 garlic cloves (minced)\r\nSalt and pepper to taste','1. Boil noodles as per package instructions and drain.  \r\n2. Heat oil in a pan and sauté garlic.  \r\n3. Add vegetables and cook until tender.  \r\n4. Add noodles and soy sauce.  \r\n5. Toss well and season with salt and pepper.  \r\n6. Serve hot.','3 servings','19');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('41','2 mins','5 mins','1 green tea bag or 1 tsp loose green tea leaves\r\n1 cup hot water\r\nHoney or lemon (optional)','1. Boil water and pour into a cup.  \r\n2. Add green tea bag or leaves and steep for 3-5 minutes.  \r\n3. Remove tea bag or strain leaves.  \r\n4. Add honey or lemon if desired and serve hot.','1 serving','20');
insert into `recipe_process` (`id`, `preparation_time`, `cooking_time`, `ingredients`, `recipe_procedure`, `serve`, `recipe_id`) values('44','10 mins','20 mins','4 medium ripe tomatoes,  \r\n1 small onion, finely chopped  \r\n2 garlic cloves, crushed  \r\n1-inch piece of ginger, grated  \r\n1 tsp butter or ghee,\r\n1/4 tsp black pepper powder,  \r\nSalt to taste,\r\n2 cups water ,\r\nFresh coriander leaves for garnish','1. Wash and roughly chop the tomatoes.  \r\n2. In a pan, heat the butter or ghee over medium heat. Add the chopped onion, garlic, and ginger, and sauté until the onion becomes translucent.  \r\n3. Add the chopped tomatoes and cook for 5 to 7 minutes, or until they soften.  \r\n4. Pour in 2 cups of water. Add salt and black pepper, then let the mixture simmer for about 10 minutes.  \r\n5. Allow it to cool slightly, then blend into a smooth puree using a mixer or hand blender.  \r\n6. Strain the puree to remove seeds and skin for a smoother texture.  \r\n7. Reheat the strained soup over low heat. Taste and adjust the seasoning if needed. Stir in the cream if using.  \r\n8. Serve hot, garnished with fresh coriander leaves.','2–3 servings','21');
